### PR TITLE
Fix(toc): Improve indicator performance and scroll if element is below scroll

### LINKED ISSUE #11: Au clic sur une référence bibliographique, accéder au contenu de la bonne référence
## Solution
Dans le panneau latéral : 
- ajouter un accordéon "Références bibliographiques" contenant toutes les références
- Au clic sur une référence dans le texte, scroller au bon endroit dans le panneau latéral, et inversement

## Document TEI 
Toutes les références sont dans les balises : 
```
<div type="references">
<listBibl>
```

Les références dans le texte sont dans les balises : `<ref type="bibr" target="#bib1">1</ref>`

### Gestion des balises <bibl imbriqués
Une référence peut contenir plusieurs références : 
Dans ce cas, ne pas tenir compte des attributs `xml:id="cit5a"`, `xml:id="cit5b"`... Ils ne sont pas référencés dans le texte
Image

Dans ce cas, séparer les références d'une même référence par un retour à la ligne.
Distinguer les différentes références par un espacement différent.

Image

Remonter un warning lorsque : 
- Une balise `<bibl` contient plusieurs balises `<bibl`

## Document TEI

Exemple document 5 des échantillons

id | TEI | PDF | notes
-- | -- | -- | --
603D3EF3811C50D0BA56D9E63488FDEB02A8E75F | https://api.istex.fr/document/603D3EF3811C50D0BA56D9E63488FDEB02A8E75F/fulltext/tei | https://api.istex.fr/document/603D3EF3811C50D0BA56D9E63488FDEB02A8E75F/fulltext/pdf | Citation simple (inline dans le body). Pas de bibliographie en back
91C753B08301D247A7F8E1F59166BF07E7830176 | https://api.istex.fr/document/91C753B08301D247A7F8E1F59166BF07E7830176/fulltext/tei | https://api.istex.fr/document/91C753B08301D247A7F8E1F59166BF07E7830176/fulltext/pdf | Document avec citation simple et bibliographie en back + `<bibl` imbriqué
0275F07B8658D0C5CB676870F47C2BAB59D70358 | https://api.istex.fr/document/0275F07B8658D0C5CB676870F47C2BAB59D70358/fulltext/tei | https://api.istex.fr/document/0275F07B8658D0C5CB676870F47C2BAB59D70358/fulltext/pdf | Document avec citation simple et bibliographie en back. Beaucoup de citations
EF607FE9AC98D0FA25BDEE6000DB0FF0BA4A877E | https://api.istex.fr/document/EF607FE9AC98D0FA25BDEE6000DB0FF0BA4A877E/fulltext/tei | https://api.istex.fr/document/EF607FE9AC98D0FA25BDEE6000DB0FF0BA4A877E/fulltext/pdf | Document contenant principalement des `<bibl>` contenant des éléments et du texte (virgule, texte) hors balisage

### LINKED ISSUE #15: Je souhaite rapidement  accéder à la partie du texte qui m'intéresse (sommaire)
## Contexte
Les documents peuvent être très longs et seulement une section peut intéresser le lecteur, il peut être donc être long de scroller pour y accéder

## Solution 
Ajouter une 3ème colonne à gauche : 
- Afficher le sommaire contenant les titres de niveaux
- Afficher un indicateur pour connaître la  section courante
- Au clic sur une section automatiquement scroller au titre de la section 
- Afficher le sommaire en sticky
- CF figma

Version petit écran : 
- Placer le contenu du sommaire 

## Question 
- Existe t-il des documents avec des plusieurs niveaux de sous-titres ?

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #11 
Closes #15 

## Additional Checks

- [X] The PR includes **unit tests** (if not possible, describe why)
- [X] The **documentation** is up to date

### CODE REVIEW

File: packages/react-tei/src/navigation/DocumentNavigationContext.tsx [hunk 1]
```diff
@@ -219,7 +234,21 @@ export function DocumentNavigationContextProvider({
 							? intersectingElement.target.getAttribute("aria-labelledby")
 							: intersectingElement.target.id;
 
-					setCurrentHeadingId(id);
+					if (!tocRef.current || !id) {
+						return;
+					}
+
+					// This is an anti-pattern for react, but this improves performance a lot, especially on large documents by avoiding re-renders
+					tocRef.current.querySelectorAll("[aria-current]").forEach((el) => {
```
Comment (ThieryMichel) [inline packages/react-tei/src/navigation/DocumentNavigationContext.tsx]: Can we have several element with aria-current at once ?

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

File: packages/react-tei/src/navigation/DocumentNavigationContext.tsx (hunk 1 above)
Comment (jonathanarnault) [reply packages/react-tei/src/navigation/DocumentNavigationContext.tsx]: In theory no, but this would prevent the case where we have many (which should not happen)

**Review by ThieryMichel — APPROVED** [review]
