### PR TITLE
Fix(sidePanel): Open sidepanel if closed when clicking on a sidenote

### LINKED ISSUE #148: Lorsque le panneau latéral est fermé et que je clique sur une référence, je n'ai plus accès au bouton pour ouvrir le panneau latéral
Comment reproduire : 
- Je ferme le panneau latéral
- je clique une première fois sur une référence : je vois le panneau latéral scroller mais le bouton pour l'agrandir disparaît
- je clique une deuxième fois sur une référence : le panneau s'ouvre bien 

Screen vidéo sur Mattermost : https://mattermost.inist.fr/projets/pl/xkoabnda638jpx37p8zxxk4zww

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #148 

https://github.com/user-attachments/assets/4a4ac6e7-bcb2-4772-a133-6595cd7bc7be

## Additional Checks

- [X] The PR includes **unit tests** (if not possible, describe why)
- [X] The **documentation** is up to date

### CODE REVIEW

File: packages/react-tei/src/navigation/DocumentNavigationContext.tsx [hunk 1]
```diff
@@ -169,52 +172,42 @@ export function DocumentNavigationContextProvider({
...
 				return;
 			}
 
+			if (!panel.state.sections[section]) {
+				panel.toggleSection(section);
+				await new Promise((resolve) => setTimeout(resolve, 300));
+			} else if (!panel.state.isOpen) {
+				panel.togglePanel();
+				await new Promise((resolve) => setTimeout(resolve, 300));
+			}
```
Comment (ThieryMichel) [inline packages/react-tei/src/navigation/DocumentNavigationContext.tsx:189]: Or you could just do:

```suggestion
			if (!panel.state.isOpen || !panel.state.sections[section]) {
				panel.toggleSection(section);
				await new Promise((resolve) => setTimeout(
				    resolve, 
				    !panel.state.isOpen && !panel.state.sections[section] ? 600 : 300
				));
			}
```
toggleSection open the panel if it is closed.
Also, you need to wait 600 if both animation (panel and section) are triggered

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
