### PR TITLE
Fix(abstract): Do not render abstract with head=Highlights

### LINKED ISSUE #98: Résumé: Ne pas prendre en compte les highlights
## Problème

Les documents Elsevier peuvent avoir des abstract pour une même langue: un résumé et un highlight.

## Solution

Ne pas afficher les abtract de type `Highlights`

## Données de Test

| ID Du Document | TEI |
| --- | --- |
| ark:/67375/6H6-TXF94B30-4 | https://api.istex.fr/ark:/67375/6H6-TXF94B30-4/fulltext.tei |

## Tech details

Filtrer les abstracts qui ont la balise suivante: `<head>Highlights</head>` (présente uniquement chez Elsevier)

### LINKED ISSUE #107: Corps de texte non rendu pour certains résumés et corps de texte
Bug signalé par @MathildeHuguin

 Le résumé présent dans la balise `abstract` de la TEI n'est pas toujours repris (ex. *OA-Scielo* [9C100A35425D290A5607007A869BE78F861596A0](https://api.istex.fr/document/9C100A35425D290A5607007A869BE78F861596A0/fulltext/tei) découpé en `<p>` et `<s>`). 

Idem pour le corps de texte : [9C100A35425D290A5607007A869BE78F861596A0](https://api.istex.fr/document/9C100A35425D290A5607007A869BE78F861596A0/fulltext/tei)

Si la balise `<s>` (issue de Grobid) ne doit pas être prise en compte elle même, les éléments enfants doivent apparaître.

### PR DESCRIPTION
**Pull request by jonathanarnault**
Closes #98 
Closes #107 

## Additional Checks

- [X] The PR includes **unit tests** (if not possible, describe why)
- [X] The **documentation** is up to date

### CODE REVIEW

File: packages/react-tei/src/abstract/useDocumentAbstracts.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { useMemo } from "react";
+import { findChildrenByName } from "../helper/findChildrenByName";
+import { findTagByName } from "../helper/findTagByName";
+import type { DocumentJson } from "../parser/document";
+
+export const UNSUPPORTED_ABSTRACT_HEAD = "highlights";
```
Comment (ThieryMichel) [inline packages/react-tei/src/abstract/useDocumentAbstracts.tsx]: It should be an array, unless you want to forbid head with value of hight or light.
```suggestion
export const UNSUPPORTED_ABSTRACT_HEAD = ["highlights"];
```

**Review by ThieryMichel — CHANGES_REQUESTED** [review]

**Review by ThieryMichel — APPROVED** [review]
